### PR TITLE
Upstream 2.36.5

### PR DESCRIPTION
**Pull request by dabio**

### CODE REVIEW

**Comment by dabio** [comment]
@jeffsheltren, @carlwgeorge, any idea when this will be deployed? Can I help you somehow?

**Review by jeffsheltren — APPROVED** [review]
Looks good, thanks. Sorry for the delay.

**Comment by jeffsheltren** [comment]
git236-2.36.5-1.el7.ius has been pushed to IUS testing

**Comment by dabio** [comment]
@jeffsheltren, how long does it usually take for a package to be promoted from testing to stable?

**Comment by jeffsheltren** [comment]
Hi, we aim for a week unless it's critical or we get testing feedback ahead of that. I'll aim to push this out today.

**Pull request merged**
